// src/auth/team-role-permissions.map.ts
import { TEAM_ROLES } from './team-roles.constants';
import { PERMISSIONS } from './permissions.constants';

export const TEAM_ROLE_PERMISSIONS: Record<string, string[]> = {
  [TEAM_ROLES.DESIGNER]: [PERMISSIONS.EDIT_REQUESTS, PERMISSIONS.UPLOAD_FILES],
  [TEAM_ROLES.SUCCESS_MANAGER]: [
    PERMISSIONS.MANAGE_CLIENTS,
    PERMISSIONS.MANAGE_REQUESTS,
    PERMISSIONS.MANAGE_DASHBOARD,
    PERMISSIONS.MANAGE_FILES,
    PERMISSIONS.MANAGE_CALENDAR,
    PERMISSIONS.MANAGE_WORKSPACE,
    PERMISSIONS.MANAGE_MEMBERS,
    PERMISSIONS.MANAGE_COMMENTS,
    PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.MANAGE_ANALYTICS,
    PERMISSIONS.MANAGE_TEMPLATES,
    PERMISSIONS.MANAGE_METRICS,
    PERMISSIONS.USER_ASSIGNMENTS,
    PERMISSIONS.VIEW_INTERNAL_REQUESTS,
  ],
  // ...otros teamRoles
};
